--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ACM-PocketMine-MP/UpdateNotifier
build-by-default: true
branches:
- PM5
projects:
  UpdateNotifier:
    path: ""
    model: virion
    type: library
...
